# This action builds and tests a basic image, as described here:
# https://canonical-risc-v-cookbook.readthedocs-hosted.com/en/latest/tutorial/create_image/
name: Build and test

# We allow running workflows on main, and on the 'ci' special branch used to work
# on ci/cd workflows.
on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install apt dependencies
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y snapd qemu-user-static ubuntu-dev-tools
      - name: Refresh systemd-binfmt
        run: sudo systemctl restart systemd-binfmt
      - name: Install ubuntu-image
        run: sudo snap install --classic ubuntu-image
      - name: Build image
        run: sudo ubuntu-image --workdir work --debug classic image-definition.yaml
      - name: Install test dependencies
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y python3-pexpect opensbi qemu-system-riscv64 qemu-efi-riscv64 u-boot-qemu
      - name: Set image permissions
        run: sudo chown $USER work/ubuntu-26.04-preinstalled-server-riscv64.img
      - name: Test image
        run: python .github/workflows/test.py work/ubuntu-26.04-preinstalled-server-riscv64.img
